Azure/azure-functions-docker

host/2.0/nanoserver-1803/amd64/Dockerfile

Add support for 1803 nanoserver 

---

host/2.0/stretch/amd64/powershell.Dockerfile
host/build.vsts-ci.yml
host/release-dockerhub.vsts-ci.yml
host/release.vsts-ci.yml

This adds the PowerShell Language Worker Dockerfile.
It grabs the nupkg from the myget feed
Unzips it and places it in the host's workers folder

Add PowerShell Dockerfile

---

host/2.0/stretch/amd64/powershell.Dockerfile
host/2.0/stretch/arm32v7/powershell.Dockerfile

Update to use the package version `0.1.20-alpha`.

Update the 'powershell.Dockerfile' in both amd64 and arm32v7 folders to use the latest worker package

---

host/2.0/stretch/amd64/python.Dockerfile

Adding support for MS SQL 17 ODBC drivers. Address the issue described [here](https://github.com/Azure/azure-functions-docker/issues/43)

Adding MS SQL ODBC drivers to Python image

---

host/2.0/stretch/amd64/mesh.Dockerfile
host/2.0/stretch/amd64/powershell.Dockerfile

To the latest worker build.
cc @pragnagopa @SteveL-MSFT @daxian-dbw @asavaritayal @soninaren @ahmelsayed

Update PowerShell version

---

host/2.0/alpine/amd64/java.Dockerfile
host/build.vsts-ci.yml

ref: https://github.com/Azure/azure-functions-docker/issues/70
Hi, thanks for awesome docker images 👍 
I thought development would become more easy with the official docker image so I made it.
It might be better that adding test code, but I could not push Java test functions to https://functionstests.blob.core.windows.net/public/docker/~~ .
So I do not have a test code, sorry.

Add java.Dockerfile for alpine

---

host/2.0/stretch/amd64/appservice/dotnet.Dockerfile
host/2.0/stretch/amd64/appservice/node.Dockerfile
host/2.0/stretch/amd64/appservice/powershell.Dockerfile
host/2.0/stretch/amd64/appservice/python.Dockerfile
host/2.0/stretch/amd64/appservice/sshd_config
host/2.0/stretch/amd64/appservice/start.sh
host/build.vsts-ci.yml
host/release.vsts-ci.yml

Add appservice images with ssh-server and debuggers

---

host/2.0/stretch/amd64/python.Dockerfile

Signed-off-by: John Howard <jhoward@microsoft.com>
@ahmetsayed Following on from internal email. This will remove 3 layers from the base functions image used to build `mcr.microsoft.com/azure-functions/mesh:2.0.12332`.  Removing 3 layers will remove 3 hot-adds of VHDs to the UtilityVM which should reduce container start time by circa 100ms.
@jterry75 FYI

Reduce layers in python.Dockerfile

---

host/2.0/alpine/amd64/python-context/start.sh
host/2.0/stretch/amd64/python-context/start.sh

Needed to fix https://github.com/Azure/azure-functions-python-worker/issues/434

Flip priority of user and system dependencies

---

host/2.0/stretch/amd64/appservice/java8.Dockerfile
host/3.0/buster/amd64/appservice/java8.Dockerfile

This pull request to update the appservice images to use azule jre.

Update the with jre instead of the jdk, add ssh

---

host/2.0/stretch/amd64/python/python36-deps.Dockerfile
host/2.0/stretch/amd64/python/python37-deps.Dockerfile
host/3.0/buster/amd64/python/python36-deps.Dockerfile
host/3.0/buster/amd64/python/python37-deps.Dockerfile

Addresses https://github.com/Azure/azure-functions-core-tools/issues/1620 and https://github.com/Azure/azure-functions-python-worker/issues/560

Add binutils to python images

---

host/build.vsts-ci.yml
kudulite/build.vsts-ci.yml

Only build KuduLite image when kudulite/* content has changed

Add selective CI build on specific content change

---

build/python.sh
host/3.0/buster/amd64/appservice/python38.Dockerfile
host/3.0/buster/amd64/python/python38-buildenv.Dockerfile
host/3.0/buster/amd64/python/python38-deps.Dockerfile
host/3.0/buster/amd64/python/python38.Dockerfile

Todo:
Wait for V3 Host build https://github.com/Azure/azure-functions-host/pull/5448

Add python 3.8 image build

---

kudulite/Dockerfile

Same as https://github.com/Azure-App-Service/KuduLiteBuild/commit/df9ced61c755ff2b212475c2301c70bf5e81c8c6

Upgrade oryx build image to 20191216.3

---

build/python.sh

Missing an 8 in python.sh build process

Fix missing character in Python 3.8

---

build/python.sh
host/3.0/buster/amd64/appservice/python38.Dockerfile
host/3.0/buster/amd64/base.Dockerfile
host/3.0/buster/amd64/powershell6.Dockerfile
host/3.0/buster/amd64/python/python38-buildenv.Dockerfile
host/3.0/buster/amd64/python/python38-deps.Dockerfile
host/3.0/buster/amd64/python/python38.Dockerfile
kudulite/Dockerfile
kudulite/build.sh

Stop Python 3.8 build in V2.0
Upgrade Oryx Build image to 20200114.13 after discussing with Gabriel Castro
Add --no-cache flag in Kudulite build

Fix build pipeline

---

host/2.0/alpine/amd64/base.Dockerfile
host/2.0/alpine/amd64/powershell.Dockerfile
host/2.0/stretch/amd64/base.Dockerfile
host/2.0/stretch/amd64/powershell6.Dockerfile

v2 Host hotfix

---

build/java.sh

@ahmelsayed I updated to use the latest java version to compile the code, https://hub.docker.com/_/microsoft-java-maven
cc @anirudhgarg

Update the build java version to latest code

---

kudulite/Dockerfile

Update kudulite base image oryx build to 20200310.1

---

host/2.0/publish-appservice-stage.yml
host/2.0/publish.yml
host/3.0/publish-appservice-stage.yml
host/3.0/publish.yml

Add release files for appservice stages

---

README.md
host/3.0/buster/amd64/dotnet/dotnet-core-tools.Dockerfile
host/3.0/dotnet-build.yml
host/3.0/publish.yml

This PR for the core-tools for the dotnet sdk 3.1 implementation with pipeline.

Add support for dotnet sdk 3.1 for core-tools

---

host/3.0/buster/amd64/java/java8/java8-appservice.Dockerfile
host/3.0/buster/amd64/java/java8/java8-slim.Dockerfile
host/3.0/buster/amd64/java/java8/java8.Dockerfile

Java changes were made after I made the PR to update the Host version, so we missed updating the version for a few of those.

Update Java 8 images Functions version

---

host/3.0/publish.yml

Some of the core-tools images was tagged from appservice image. 
I fixed it.

fix: Wrong tag target

---

README.md
test/image-healthcheck.yml

I implement a simple health check pipeline to avoid build image shortage. This pipeline will: 
* run hourly 
* check the status of core-tools images
* compare the version of the core tools with latest (warning message only)
* If the image broken, it notify me
* Status Badge on README
Pipeline:
https://azure-functions.visualstudio.com/azure-functions-docker/_build?definitionId=43&_a=summary

Implement Image Health Check for the core tools

---

host/3.0/core-tools-publish.yml

The nightly build running around 15:30 (PDT) 
I change it to the 22:30 (PDT)

Change time of the nightly build

---

README.md
host/3.0/buster/amd64/powershell/powershell6-core-tools.Dockerfile
host/3.0/buster/amd64/powershell/powershell7-core-tools.Dockerfile
host/3.0/core-tools-publish.yml

This PR is follow up PR of this PR. After the PR has been published, a lot of change made to master, to avoid rollback, I create a new PR from scratch, however, this PR is based on the PR, and expand to PowerShell7. 
https://github.com/Azure/azure-functions-docker/pull/253
I implement all request from @AnatoliB 
Could you have a look? 
* PowerShell6 Core Tools (Azure CLI, AzModule, Core Tools V3)
* PowerShell7 Core Tools (Azure CLI, AzModule, Core Tools V3)
* Pipeline Build, Test, Publish
* Documentation
The Pipeline is already tested.  The pipeline will run 10:30.

PowerShell 6, 7 images and pipeline and Documentation

---

test/image-healthcheck.yml

It stop scheduled timer. recover it again by a commit.

Commit for recovering Health check trigger

---

host/2.0/dotnet-build.yml
host/2.0/java-build.yml
host/2.0/nanoserver-build.yml
host/2.0/node-build.yml
host/2.0/powershell-build.yml
host/2.0/python-build.yml
host/3.0/dotnet-build.yml
host/3.0/java-build.yml
host/3.0/nanoserver-build.yml
host/3.0/node-build.yml
host/3.0/powershell-build.yml
host/3.0/python-build.yml

Publish v2 and Publish v3 will not get trigger automatically. Manual intervention required.

Automatically trigger language worker image build on tag 2.0.x or 3.0.x

---

host/3.0/buster/amd64/powershell/powershell7-core-tools.Dockerfile

Remove duplicated "less" entry from the list of utilities to install.

Remove duplicated "less" entry

---

host/3.0/buster/amd64/node/node14/node14-appservice.Dockerfile
host/3.0/buster/amd64/node/node14/node14-core-tools.Dockerfile
host/3.0/buster/amd64/node/node14/node14-slim.Dockerfile
host/3.0/buster/amd64/node/node14/node14.Dockerfile
host/3.0/buster/amd64/node/node14/sshd_config
host/3.0/buster/amd64/node/node14/start.sh
host/3.0/core-tools-publish.yml
host/3.0/node-build.yml
host/3.0/publish-appservice-stage.yml
host/3.0/publish.yml

- [X ] The title of the PR is clear and informative.
- [X ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

Adding node14 images

---

host/3.0/publish.yml

[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)
---

Fixing v3 publish pipeline for node14

---

host/3.0/buster/amd64/java/java11/java11-appservice.Dockerfile
host/3.0/buster/amd64/java/java11/java11-slim.Dockerfile
host/3.0/buster/amd64/java/java11/java11.Dockerfile
host/3.0/buster/amd64/java/java8/java8-appservice.Dockerfile
host/3.0/buster/amd64/java/java8/java8-slim.Dockerfile
host/3.0/buster/amd64/java/java8/java8.Dockerfile

Upgrade the Java8 and Java11 images

Upgrade Java to 8u252 and 11u7

---

host/3.0/buster/amd64/python/python39/python39-appservice.Dockerfile
host/3.0/buster/amd64/python/python39/python39-buildenv.Dockerfile
host/3.0/buster/amd64/python/python39/python39-core-tools.Dockerfile
host/3.0/buster/amd64/python/python39/python39-slim.Dockerfile
host/3.0/buster/amd64/python/python39/python39.Dockerfile
host/3.0/buster/amd64/python/python39/sshd_config
host/3.0/buster/amd64/python/python39/start.sh
host/3.0/python-build.yml

Added Python 3.9 images:
- app service
- custom base image
- build environment
- core tools
Todo:
- Update core-tools-publish.yml to use the latest Python 3.9 image when it is stable.
---

Add Python 3.9 images

---

README.md
host/3.0/publish-appservice-stage.yml
host/3.0/publish.yml

- Added Python 3.9 images to publish pipeline
- Added Python 3.9 images to README.md
---

Add Python 3.9 images to publish pipeline

---

host/2.0-upgrade/publish-appservice-stage.yml

[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)
---

Fix python upgrade build yaml

---

host/2.0-upgrade/stretch/amd64/dotnet/dotnet-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/node/node10/node10-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/node/node8/node8-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/python/python36/python36-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/python/python37/python37-appservice.Dockerfile

[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)
---

Upgrade host version to 3.0.15277 for auto-upgraded apps

---

host/2.0/stretch/amd64/dotnet/dotnet-appservice.Dockerfile
host/3.0/buster/amd64/dotnet/dotnet-appservice.Dockerfile

[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)
---

Add chrome-headless deps to appservice dotnet images

---

host/2.0-upgrade/stretch/amd64/dotnet/dotnet-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/node/node10/node10-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/node/node8/node8-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/python/python36/python36-appservice.Dockerfile
host/2.0-upgrade/stretch/amd64/python/python37/python37-appservice.Dockerfile

[V3 Release](https://github.com/Azure/azure-functions-host/releases/tag/v3.0.15352)
---

Update host version to 3.0.15352 for auto-upgraded apps.
