host/2.0/stretch/amd64/Dockerfile

With CMD without [] there are two processes running in the container.

Modify Dockerfile not to spawn two processes

---

host/2.0/stretch/amd64/python-context/start.sh

This change is part of the PR - https://github.com/Azure/azure-functions-core-tools/pull/792
I was wondering if there's a specific reason we use a venv in the container? I have removed it in this PR, but I can add it back if we would still need it.

Modify start.sh to use the bundled python worker

---

host/2.0/alpine/amd64/base.Dockerfile
host/2.0/alpine/amd64/powershell.Dockerfile

This fixes the following error while building the alpine images:
> apt-get: not found

Replace apt-get with apk in alpine images

---

host/2.0/stretch/amd64/appservice/start.sh

Ran into an issue recently where `--server` syntax is no longer usable for recent versions of `ptvsd`. Modified to `--host localhost` instead which has the same functional behavior.

Using localhost syntax for recent ptvsd versions

---

kudulite/Dockerfile
kudulite/startup.sh

We need to have our own kudulite's docker image, because this image
1. exposes port 80 and bind it to kestrel server
2. stripped off webssh
Please let me know if this is the right place to place the docker file.
If so, build.sh will be updated in the next PR.

Add kudulite Dockerfile for linux consumption

---

kudulite/Dockerfile
kudulite/build.sh
kudulite/build.vsts-ci.yml
kudulite/release.vsts-ci.yml
kudulite/tag.sh

1. We can build a kudulite image with `./build.sh kudulite <tagname>`
2. The temporary built image will always be mcr.microsoft.com/azure-functions/kudulite:dev
3. Every release will tag the built image into
- mcr.microsoft.com/azure-functions/kudulite:latest
- mcr.microsoft.com/azure-functions/kudulite:$(ReleaseVersion)
Update oryx build to 20190704.2

Add kudulite in build and release process

---

kudulite/Dockerfile
kudulite/build.sh

Since dotnet core 3.0 is released, the dotnet-aspnet-codegenerator nuget package has the latest version of 3.0 which breaks the build.
We need to pin its version to 2.2.4 to compile kudulite project.

Pin KuduLite aspnetcore code generator to version 2.2.4

---

host/2.0/stretch/amd64/python/python36.Dockerfile
host/2.0/stretch/amd64/python/python37.Dockerfile

@ahmelsayed, this should fix the resolution of dependencies. If you want to try it out with your own image in the  meantime to unblock, you can run with `-e "FUNCTIONS_WORKER_RUNTIME_VERSION=3.7"`.

Add runtime versions for 3.6/3.7

---

host/2.0/nanoserver/1803/dotnet.Dockerfile
host/2.0/nanoserver/1809/dotnet.Dockerfile
host/2.0/nanoserver/1903/dotnet.Dockerfile
host/3.0/nanoserver/1809/dotnet.Dockerfile
host/3.0/nanoserver/1903/dotnet.Dockerfile
host/3.0/nanoserver/1909/dotnet.Dockerfile

Fix nano server build:
Since the old build in https://github.com/Azure/azure-functions-docker/pull/235 has lost,
and it is now blocking Linux Consumption release https://github.com/Azure/azure-functions-docker/pull/241
I duplicate the PR and check if the build status will pass

Fix Nano Server Build

---

README.md
host/3.0/buster/amd64/node/node10/node10-core-tools.Dockerfile
host/3.0/buster/amd64/node/node12/node12-core-tools.Dockerfile
host/3.0/node-build.yml
host/3.0/publish.yml

Adding Azure Functions Core Tools v3 images for the Node 10, 12
The base image is `mcr.microsoft.com/vscode/devcontainers/javascript-node:10`.  It references https://github.com/microsoft/vscode-dev-containers/blob/master/containers/javascript-node-10/.devcontainer/Dockerfile image on the `vscode-dev-containers`.  Should we depend on it or should we create a new one from scratch? 
Currently, the Dockerfile is moved from the vscode dev-containers repo. These image is going to reference our images. 
* https://github.com/microsoft/vscode-dev-containers/tree/master/containers/azure-functions-node-10
* https://github.com/microsoft/vscode-dev-containers/tree/master/containers/azure-functions-node-12
The ancestor is debian 9 
https://hub.docker.com/_/debian

Azure Functions Core Tools Node images

---

host/3.0/buster/amd64/java/java8-core-tools.Dockerfile

VSCode DevContainer proivde common script that user enables to use zsh option for example. For enabling this scenario, I'd like to add unzip and wget. These library is also usefrul for CI scenario. 
https://github.com/microsoft/vscode-dev-containers/pull/311
In the vscode-dev-container repo, they will add this script. It requires wget and unzip. 
```bash
ARG INSTALL_ZSH=true
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN curl -ssL https://raw.githubusercontent.com/microsoft/vscode-dev-containers/master/script-library/common-debian.sh -o /tmp/setup-script.sh \
&& /bin/bash /tmp/common-setup.sh "$INSTALL_ZSH" "$USERNAME" "$USER_UID" "$USER_GID" \
&& rm /tmp/common-setup.sh
```

Add unzip and wget to support Common-Script

---

README.md
host/3.0/buster/amd64/python/python38/python38-core-tools.Dockerfile
host/3.0/publish.yml
host/3.0/python-build.yml

I create a core tools for python.
This PR includes:
1. Core Tools image with python 3.8
2. Enable trigger for 3.8 to build python images.
3. Add pipeline code to enable 3.8 python images.

Python Core Tools and Version bump to 3.8

---

host/2.0/publish.yml
host/2.0/python-build.yml
host/3.0/publish.yml
host/3.0/python-build.yml

Bug:
The current V3 Pipeline is tagging Python 3.7 as the default image in V3

Tag Python 3.6 as default Python image in V3

---

host/2.0/publish.yml

It looks like we don't build alpine images anymore. This causes the publish steps to fail.

Remove alpine Python publish step

---

host/3.0/node-build.yml

The CI or master build wasn't triggering for the changes in node dockerfiles. This meant some updates were being missed.

Fix node CI trigger paths

---

host/2.0/publish.yml

We don't build Python 3.8 images for v2.
Sorry about so many individual PRs. I am fixing these as build pipeline fails with new errors. I am hoping this is the last one.

Remove Python 3.8 from v2

---

host/3.0/python-build.yml

I found an issue that python 3.8 core-tools images is based on wrong images. 
I also find, sometimes, it causes lack of capacity. 
Refer this pipeline execution: https://azure-functions.visualstudio.com/azure-functions-docker/_build/results?buildId=1569&view=results
```
Error processing tar file(exit status 1): write /usr/lib/azure-functions-core-tools-3/workers/powershell/runtimes/linux/native/libgrpc_csharp_ext.x64.so: no space left on device
2020-05-15T00:45:47.3568743Z 
```
For fixing this I've done:
* Point the correct core-tools image and add testing (it was not there) 
* Using Jobs for parallel execution
* Upgrade ubuntu agent from 16.04 -> 18.04. The old version have opportunity to pick old slow vm.
* Use BuildKit  https://docs.docker.com/develop/develop-images/build_enhancements/ …

Fix: Python core-tools with CI improvement

---

host/3.0/java-build.yml
host/3.0/node-build.yml
host/3.0/publish.yml
host/3.0/python-build.yml

I'm migrating Core Tools Build / Publish to the Nightly build. 
So I separate the pipeline. I also find my old  YAML file has a bug of tagging wrong. 
Until the pipeline finished, I'd like to remove the core-tools build/publishing to avoid 
to push wrong image.

Remove Core Tools Build Publish

---

core-tools-pipeline.md
host/3.0/buster/amd64/dotnet/dotnet-core-tools.Dockerfile
host/3.0/buster/amd64/node/node10/node10-core-tools.Dockerfile
host/3.0/buster/amd64/node/node12/node12-core-tools.Dockerfile
host/3.0/core-tools-publish.yml
host/3.0/dotnet-build.yml

This pipeline is Nightly Build Pipeline for publishing Azure Functions Core Tools.  Include documentation for this pipeline. 
The pipeline has multi stage. 
Fetch the latest version of Azure Functions Core Tools. The version will be
`TargetVersion`. (e.g. 3.0.2534)  Also this stage fetch the weekday (0-6). 
Build and Test images then publish images with `PrivateVersion`.  The `PrivateVersion` will be `TargetVersion` + weekday(0-6). (e.g. 3.0.2534.3)
Pull images from Private Docker Registry with `PrivateVersion` then publish with `TargetVersion` and `MajorVersion` (e.g. 3.0) 
Pipeline has several mode for testing Dockerfile, Pipeline, and Rollback the images in case of the images are broken. For more details, please refer the documentation. 
The document covers both scenario. 
PowerShell …

Implement core-tools nightly build pipeline

---

kudulite/Dockerfile
kudulite/mesh/go.mod
kudulite/mesh/main.go
kudulite/mesh/pkg/logger/logger.go
kudulite/mesh/pkg/mount/mount.go
kudulite/startup.sh

Adds support to mount Azure file shares in Kudulite. This will provide persistent storage in linux consumption scm sites.
https://github.com/Azure-App-Service/KuduLite/pull/121
uses this feature to store deployment logs.

Add Azure files mount support in Kudulite

---

CODEOWNER

Adding a new CODEOWNERS file to automatically add code owners as reviewers to any new PRs.

Adding new CODEOWNERS file

---

host/2.0/stretch/amd64/dotnet/dotnet-appservice.Dockerfile
host/2.0/stretch/amd64/dotnet/dotnet-slim.Dockerfile
host/2.0/stretch/amd64/dotnet/dotnet.Dockerfile
host/2.0/stretch/amd64/java/java8-appservice.Dockerfile
host/2.0/stretch/amd64/java/java8-slim.Dockerfile
host/2.0/stretch/amd64/java/java8.Dockerfile
host/2.0/stretch/amd64/node/node10/node10-appservice.Dockerfile
host/2.0/stretch/amd64/node/node10/node10-slim.Dockerfile
host/2.0/stretch/amd64/node/node10/node10.Dockerfile
host/2.0/stretch/amd64/node/node12/node12-appservice.Dockerfile
host/2.0/stretch/amd64/node/node12/node12-slim.Dockerfile
host/2.0/stretch/amd64/node/node12/node12.Dockerfile
host/2.0/stretch/amd64/node/node8/node8-appservice.Dockerfile
host/2.0/stretch/amd64/node/node8/node8-slim.Dockerfile
host/2.0/stretch/amd64/node/node8/node8.Dockerfile

updated runtime-deps:2.2 image is no longer available.

Use runtime-deps:2.1 for V2 images to get latest os updates 

---

host/3.0/buster/amd64/java/java11/java11-appservice.Dockerfile
host/3.0/buster/amd64/java/java11/java11-slim.Dockerfile
host/3.0/buster/amd64/java/java11/java11.Dockerfile
host/3.0/buster/amd64/java/java8/java8-appservice.Dockerfile
host/3.0/buster/amd64/java/java8/java8-slim.Dockerfile
host/3.0/buster/amd64/java/java8/java8.Dockerfile

- We are upgrading the java run time to be aligned with Ant89.
- We are using debian10 images.
- We are using with tools that will support jstack and jcmd tooling.

Upgrade java versions

---

kudulite/build.sh
kudulite/build.vsts-ci.yml
test/kudulite/containers.ts
test/kudulite/index.ts
test/kudulite/interfaces.ts
test/kudulite/testcases.ts
test/kudulite/utils.ts
test/package-lock.json
test/package.json

Everytime when we release a new kudulite image, it takes quite a long time for the OGF to finish. We want to automate this process.
**containers.ts** The main component of this system. It in charge of creating new kudulite container on local machine (build agent),  configure the kudulite container, orchestrate a remote build. Also, it validates if the built artifact can be run on those runtime images (e.g. mcr.microsoft.com/azure-functions/python:3.0-python3.6-appservice).
**testcases.ts** The place where we define testing different remote build scenarios.
**utils.ts** The sleeper and retrier.
1. We upload the source project zip file (e.g. python36_src.zip) to source container
2. The program will first initialize a KuduLite container for remote build service
1. setting up environment …

Add test infrastructure for remote build

---

kudulite/Dockerfile
kudulite/build.sh
kudulite/build.vsts-ci.yml
kudulite/publish.sh
kudulite/startup.sh
kudulite/test.sh
test/kudulite/containers.ts
test/kudulite/index.ts

Previously our KuduLite image reaches 8.78GB and Atlas team has hard time caching our images.
In this PR, I made a few improvements to reduce the image size:
1. Turning on ENABLE_DYNAMIC_INSTALL, this is a Oryx feature to lazy load deployment tools (e.g. pip, npm, dotnet) only when customer triggers a build.
2. Clean up built-in SDKs by removing python, php, hugo and stripping nodejs!=9 and dotnet~2.
3. Squash the final image into a single layer.
1. Update KuduLite website to use .NetCore 3.1
Building the image from https://github.com/Hazhzeng/KuduLite/tree/hazeng-stage.
Uploaded the image to docker hub rogerxman/test:kudu-one and tested on private stamp.
The newly generated image now takes 3.01 GB.

Reduce KuduLite image size

---

kudulite/Dockerfile
kudulite/startup.sh
test/kudulite/containers.ts
test/kudulite/index.ts
test/kudulite/testcases.ts

**Background:**
The kudu-2.12 image has an issue due to Oryx Build fails to resolve netcoreapp2.2 extensions a proper sdk.
Netcoreapp2.2 will always point to 2.2.8 runtime (sdk 2.2.207) where the SDK version is older then 2.2.7 runtime (sdk 2.2.402).
This conflict yields to an issue when resolving the extensions.csproj in remote build.
**Mitigation:**
Still waiting for the fix on Oryx Build side. To mitigate, I made a symbolic link points 2.2.8 to 2.2.7 runtime.
**Micellaneous:**
Added a few more test cases for
1. dotnet 2.x and  dotnet 3.x
2. python with dotnet extensions
3. overwrite WEBSITE_RUN_FROM_PACKAGE app setting in api/zipdeploy endpoint

Mitigate reference error in dotnet 2.2

---

kudulite/Dockerfile
kudulite/startup.sh
test/kudulite/index.ts
test/kudulite/testcases.ts

Fixes https://github.com/Azure/azure-functions-core-tools/issues/2243
This is an issue in the old oryx image mcr.microsoft.com/oryx/build:20200813.1.
Thanks for the help @kichalla as we discussed offline, the new image addresses a few issue:
1. dotnet runtime 2.2.8 and sdk 2.2.207 are now available in the remote build, no longer need the symbolic link to make it work
`RUN ln -s /opt/dotnet/runtimes/2.2.7 /opt/dotnet/runtimes/2.2.8`.
2. npm comes with nodejs, we can trim off npm folder completely to further reduce image size.
3. Python library linking issue (e.g. -lpython3.6m) is fixed.
Added a new test scenario for resolving **pyodbc** Python module.
https://kuduliteimagetest.blob.core.windows.net/testsrc/KuduLitePythonBuildWheel.zip?sv=2019-02-02&st=2020-09-29T23%3A47%3A37Z&se=2024-09-30T …

Fix Python library (-lpython3xm.so) link failure in remote build

---

host/3.0/buster/amd64/powershell/powershell7-core-tools.Dockerfile

Bumped PowerShell version to 7.0.3 as this is now the latest stable release.
There is no PowerShell 7 version in the build YAML in the repo for the 3.0 hosts. I can have a go at adding this based on the PowerShell 6 examples.

Bumped PowerShell version to 7.0.3

---

host/3.0/buster/amd64/powershell/powershell6-core-tools.Dockerfile

https://github.com/PowerShell/Announcements/issues/20
@AnatoliB @Francisco-Gamino 
We update the PowerShell for fixing CVE-2020-1108 . 
Fixed version. 
7.0 | 7.0.2
-- | --
6.2 | 6.2.6

Fix: CVE-2020-1108: .NET Core Denial of Service Vulnerability

---

host/3.0/dotnet-build.yml
host/3.0/java-build.yml
host/3.0/nanoserver-build.yml
host/3.0/node-build.yml
host/3.0/powershell-build.yml
host/3.0/python-build.yml

This PR is a part of the Release. I follow the [instruction step 3](https://github.com/Azure/azure-functions-docker/wiki/Releasing-images-for-Linux-Dedicated). This PR marge release 3.x branch to master.  This is a part of 3.0.15277 release process.
Since there was 3 commit ahead master on the release/3.x branch. However, these change is already reside on the master. 
Only the difference between master and release/3.x is adding release/3.x branch as Ci trigger. 
I'm not sure if it is needed for master branch or not. 
The original HotFix and Cherry Pick was, the Functions Host version (it will be updated this time) and Extension Bundle 
version. It was done by @divyagandhii .

Merge release/3.x branch to master
